name: Build Kenzo Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout Kernel Source
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install Extra Build Tools
      run: |
        sudo apt-get update
        sudo apt-get install -y bc build-essential libncurses5-dev libssl-dev tcl \
        bison flex libelf-dev git zip ccache cpio gcc-aarch64-linux-gnu

    - name: Compile Kernel
      run: |
        export ARCH=arm64
        export SUBARCH=arm64
        export CROSS_COMPILE=aarch64-linux-gnu-

        make O=out kenzo_defconfig
        make -j$(nprocs) O=out

    - name: Pack with AnyKernel3
      run: |
        cp out/arch/arm64/boot/Image.gz-dtb AnyKernel3/
        cd AnyKernel3
        zip -r9 ../Kenzo-Kernel-Software-Keystore.zip * -x .git README.md

    - name: Upload Finished Kernel
      uses: actions/upload-artifact@v4
      with:
        name: Kenzo-Kernel-Zip
        path: Kenzo-Kernel-Software-Keystore.zip
